// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpqTkpC1GtOrxkWufPhHWxE6rFRHpvU6Q',
    appId: '1:655205469486:web:0f1fceb9a9c4b7cc93bebf',
    messagingSenderId: '655205469486',
    projectId: 'mycrud-17e41',
    authDomain: 'mycrud-17e41.firebaseapp.com',
    storageBucket: 'mycrud-17e41.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_l0LSIwmyv2uKR24Z9whXvYM_rsJAVSk',
    appId: '1:655205469486:android:1489185dcd1e8ca993bebf',
    messagingSenderId: '655205469486',
    projectId: 'mycrud-17e41',
    storageBucket: 'mycrud-17e41.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvjYKnkMnHVaZe-hGi4jYMkSo9bkurjkk',
    appId: '1:655205469486:ios:69f98096ba816e0893bebf',
    messagingSenderId: '655205469486',
    projectId: 'mycrud-17e41',
    storageBucket: 'mycrud-17e41.firebasestorage.app',
    iosBundleId: 'com.example.lec17Firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvjYKnkMnHVaZe-hGi4jYMkSo9bkurjkk',
    appId: '1:655205469486:ios:69f98096ba816e0893bebf',
    messagingSenderId: '655205469486',
    projectId: 'mycrud-17e41',
    storageBucket: 'mycrud-17e41.firebasestorage.app',
    iosBundleId: 'com.example.lec17Firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpqTkpC1GtOrxkWufPhHWxE6rFRHpvU6Q',
    appId: '1:655205469486:web:8a73c326c774d3c293bebf',
    messagingSenderId: '655205469486',
    projectId: 'mycrud-17e41',
    authDomain: 'mycrud-17e41.firebaseapp.com',
    storageBucket: 'mycrud-17e41.firebasestorage.app',
  );
}
